name: Release

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

permissions:
    contents: write # needed to create GitHub Releases

jobs:
    publish:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm test --if-present

            - name: Build package
              run: pnpm build

            - name: Archive dist artifacts
              if: success()
              run: |
                  tar -czf dist.tar.gz dist || echo "no dist folder to archive"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  files: |
                      dist.tar.gz
                      package.json
                      LICENSE
                      README.md
